spring.application.name=API
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

spring.data.mongodb.uri=mongodb+srv://dmirudull:cx6K7fwGuLBvOVQ9@kotlin-notes.ie79j4j.mongodb.net/Kotlin-Notes

spring.data.mongodb.database=Kotlin-Notes

server.port=9090