spring.application.name=API
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

spring.mongodb.uri=mongodb+srv://Mirudull:huQBPCQDRlMthpTB@kotlin-notes.ie79j4j.mongodb.net?appName=Kotlin-Notes

spring.mongodb.database=Kotlin-Notes
spring.security.user.password=test

jwt.secret="1234567890-=asdfghjkl;zxcvbnm,.1234567890qwertyuiop[ASDFGHJKL"